In [ ]:
# 관련 import
import tensorflow as tf
import numpy as np  
import os, re, glob  
import cv2  
from tensorflow.keras.preprocessing.image import ImageDataGenerator, array_to_img, img_to_array, load_img
from sklearn.model_selection import train_test_split 
from keras.models import load_model
import matplotlib.pyplot as plt
from os.path import isfile, join
from os import listdir
from PIL import Image

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
# 1. data load 하기
X_train, X_test, Y_train, Y_test = np.load('/content/drive/MyDrive/Bit MiniProject/Shoes_imageDataList/imageDataList.npy', allow_pickle=True)

In [ ]:
# 2. 모델 불러오기
from keras.models import load_model
model = load_model('/content/drive/MyDrive/Bit MiniProject/Shoes_imageDataList/shoes_model.h5')


In [ ]:
# 테스트할 폴더 : 예측하고 싶은 사진
caltech_dir = "/content/drive/MyDrive/Bit MiniProject/test"

#폴더 안에 있는 파일 for문으로 설정
image_w = 64
image_h = 64

X = []
filenames = []
files = glob.glob(caltech_dir+"/*.*")
for i, f in enumerate(files):
    img = Image.open(f)
    img = img.convert("RGB")
    img = img.resize((image_w, image_h))
    data = np.asarray(img)
    filenames.append(f)
    X.append(data)

X = np.array(X) # file name 를 저장한다

prediction = model.predict(X)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
cnt = 0
categories = ['나이키-Running',"반스-Canvas", "슈펜-Canvas","아디다스-Running","아식스-Running","엑셀시오르-Canvas","컨버스-Canvas","프로스펙스-Running",'휠라-Running'] # 카테고리가 됨

#이 비교는 그냥 파일들이 있으면 해당 파일과 비교. 카테고리와 함께 비교해서 진행하는 것은 _4 파일.
for i in prediction:
    pre_ans = i.argmax()  # 예측 레이블
    print(i)
    print(pre_ans)
    pre_ans_str = ''
    if pre_ans == 0: pre_ans_str = "Other-Snekers"
    elif pre_ans == 1: pre_ans_str = "나이키-Running"
    elif pre_ans == 2: pre_ans_str = "반스-Canvas"
    elif pre_ans == 3: pre_ans_str = "슈펜-Canvas"
    elif pre_ans == 4: pre_ans_str = "아디다스-Running"
    elif pre_ans == 5: pre_ans_str = "아식스-Running"
    elif pre_ans == 6: pre_ans_str = "엑셀시오르-Canvas"
    elif pre_ans == 7: pre_ans_str = "컨버스-Canvas"
    elif pre_ans == 8: pre_ans_str = "프로스펙스-Running"
    elif pre_ans == 9: pre_ans_str = "휠라-Running"

    if i[0] >= 0.8: print("해당 "+filenames[cnt].split("//")[0]+"이미지는 \n"+pre_ans_str+"로 추정됩니다.")
    if i[1] >= 0.8: print("해당 "+filenames[cnt].split("//")[0]+"이미지는 \n"+pre_ans_str+"로 추정됩니다.")
    if i[2] >= 0.8: print("해당 "+filenames[cnt].split("//")[0]+"이미지는 \n"+pre_ans_str+"로 추정됩니다.")
    if i[3] >= 0.8: print("해당 "+filenames[cnt].split("//")[0]+"이미지는 \n"+pre_ans_str+"로 추정됩니다.")
    if i[4] >= 0.8: print("해당 "+filenames[cnt].split("//")[0]+"이미지는 \n"+pre_ans_str+"로 추정됩니다.")
    if i[5] >= 0.8: print("해당 "+filenames[cnt].split("//")[0]+"이미지는 \n"+pre_ans_str+"로 추정됩니다.")
    if i[6] >= 0.8: print("해당 "+filenames[cnt].split("//")[0]+"이미지는 \n"+pre_ans_str+"로 추정됩니다.")
    if i[7] >= 0.8: print("해당 "+filenames[cnt].split("//")[0]+"이미지는 \n"+pre_ans_str+"로 추정됩니다.")
    if i[8] >= 0.8: print("해당 "+filenames[cnt].split("//")[0]+"이미지는 \n"+pre_ans_str+"로 추정됩니다.")
    if i[9] >= 0.8: print("해당 "+filenames[cnt].split("//")[0]+"이미지는 \n"+pre_ans_str+"로 추정됩니다.")

    cnt += 1

    # print(i.argmax()) #얘가 레이블 [1. 0. 0.] 이런식으로 되어 있는 것을 숫자로 바꿔주는 것.
    # 즉 얘랑, 나중에 카테고리 데이터 불러와서 카테고리랑 비교를 해서 같으면 맞는거고, 아니면 틀린거로 취급하면 된다.
    # 이걸 한 것은 _4.py에.

[0.000 1.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000]
1
해당 /content/drive/MyDrive/Bit MiniProject/test/1.jpg이미지는 
나이키-Running로 추정됩니다.
[1.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000]
0
해당 /content/drive/MyDrive/Bit MiniProject/test/다운로드.jpg이미지는 
Other-Snekers로 추정됩니다.
[0.000 0.000 1.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000]
2
해당 /content/drive/MyDrive/Bit MiniProject/test/['[TV CF상품]']_0.jpg이미지는 
반스-Canvas로 추정됩니다.
[0.000 0.000 0.000 0.000 0.000 0.000 0.000 1.000 0.000 0.000]
7
해당 /content/drive/MyDrive/Bit MiniProject/test/['써모 펠트 척 70 러브포션 169519C']_2.jpg이미지는 
컨버스-Canvas로 추정됩니다.
[0.000 1.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000]
1
해당 /content/drive/MyDrive/Bit MiniProject/test/아디다스.jpg이미지는 
나이키-Running로 추정됩니다.
[0.000 0.000 0.000 0.000 0.000 0.000 0.000 1.000 0.000 0.000]
7
해당 /content/drive/MyDrive/Bit MiniProject/test/컨버스.jpg이미지는 
컨버스-Canvas로 추정됩니다.
[0.000 0.000 0.000 0.000 0.000 0.000 0.000 1.000 0.000 0.000]
7
해당 /con